sudo: false
language: python
python:
- '2.7'
install:
- pip install -q boto3
- pip install -q urllib2.urlopen
- pip install -q json

deploy:
  provider: "$provider"
  function_name: "$function_name"
  role: "$role"
  handler_name: "$handler_name"
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
