os: linux

sudo: false

language: python

python:
- '2.7'

install:
- pip install pip boto3 urllib3 -U

script:
- make bundle

branches:
  only:
    - master

deploy:
  provider: "$provider"
  function_name: "$function_name"
  role: "$role"
  handler_name: "$handler_name"
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
